.\" Manpage for opendlv-proxy-mantis-brake
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-proxy-mantis-brake 1 "05 November 2017" "0.0.1" "opendlv-proxy-mantis-brake man page"

.SH NAME
opendlv-proxy-mantis-brake \- This microservice is undocumented.



.SH SYNOPSIS
.B opendlv-proxy-mantis-brake --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-mantis-brake --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)
