# docker-compose.yml - Composition of micro-services to run OpenDLV software.
# Copyright (C) 2016 Chalmers Revere
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2016-09-09

version: '2'

services:
    odsupercomponent:
        image: seresearch/opendlv-lynx-on-opendlv-on-opendlv-core-on-opendavinci-on-base
        network_mode: "host"
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"

    sim-lynx-vehicle:
        image: seresearch/opendlv-lynx-on-opendlv-core-on-opendavinci-on-base
        network_mode: "host"
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv.lynx/bin/opendlv-sim-lynx-bicyclemodel --cid=${CID} --freq=10"
    
    sim-world:
        image: seresearch/opendlv-sim-on-opendlv-core-on-opendavinci-on-base
        network_mode: "host"
        depends_on:
            - odsupercomponent
        command: "/opt/opendlv.sim/bin/opendlv-sim-world --cid=${CID} --freq=10 --id=0 --verbose=0"

    ui-default:
        image: chalmersrevere/opendlv-ui-default:v0.0.1
        network_mode: "host"
        depends_on:
            - odsupercomponent

