.\" Manpage for opendlv-sim-lynx-vehicle
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-sim-lynx-vehicle 1 "06 November 2017" "0.0.2" "opendlv-sim-lynx-vehicle man page"

.SH NAME
opendlv-sim-lynx-vehicle \- This microservice is undocumented.



.SH SYNOPSIS
.B opendlv-sim-lynx-vehicle --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-sim-lynx-vehicle --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)
