.\" Manpage for opendlv-proxy-mantis-steering
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-proxy-mantis-steering 1 "05 November 2017" "0.0.1" "opendlv-proxy-mantis-steering man page"

.SH NAME
opendlv-proxy-mantis-steering \- This microservice is undocumented.



.SH SYNOPSIS
.B opendlv-proxy-mantis-steering --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-mantis-steering --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)
