.\" Manpage for opendlv-sim-world
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-sim-world 1 "08 August 2017" "0.0.1" "opendlv-sim-world man page"

.SH NAME
opendlv-sim-world \- This microservice keeps track of the simulated world state, in particular the absolute position of simulated agents and other entities.



.SH SYNOPSIS
.B opendlv-sim-world --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-sim-world --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

